name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-activity-graph
    steps:
      - uses: actions/checkout@v4
      - name: Download activity graph SVG
        run: |
          curl -s "https://github-readme-activity-graph.vercel.app/graph?username=DishnaDahamWijemanna&bg_color=0D1117&color=3B82F6&line=3B82F6&point=ffffff&area=true&hide_border=true&custom_title=Dishna%27s%20Contribution%20Activity" -o profile-activity-graph.svg
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update activity graph"
          file_pattern: "profile-activity-graph.svg"
